apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ms-email
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ms-email
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ms-email
    spec:
      containers:
        - name: ms-email
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
